(() => {
'use strict';
const $=id=>document.getElementById(id);const PIN='1234';let db=null,unsubOrders=null,unsubMenu=null;
const DEFAULT_MENU=[['Combinados','Combinado Akatsuky','Seleção especial da casa.',59.90],['Combinados','Combinado Sushi','Variedade para compartilhar.',79.90],['Sushi','Uramaki Salmão','8 unidades.',32.90],['Sushi','Hot Roll','8 unidades.',29.90],['Sashimi','Sashimi Salmão','Fatias frescas.',39.90],['Temaki','Temaki Salmão','Salmão e arroz.',28.90],['Bebidas','Refrigerante Lata','Escolha o sabor.',6],['Bebidas','Água','Água mineral.',4]].map((x,i)=>({id:i+1,cat:x[0],name:x[1],desc:x[2],price:x[3]}));
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function conn(t,c){$('connection').className='notice '+c;$('connection').textContent=t;}
function listen(){
 if(!db){conn('🔴 Firebase não carregou. Verifique a conexão.','error');return;}
 unsubOrders&&unsubOrders();unsubMenu&&unsubMenu();
 const ro=db.ref('orders');unsubOrders=ro.on('value',snap=>{const data=snap.val()||{},arr=Object.entries(data).sort((a,b)=>(b[1].createdAt||0)-(a[1].createdAt||0));$('statOrders').textContent=arr.length;$('statNew').textContent=arr.filter(x=>x[1].status==='recebido').length;$('statTotal').textContent=money(arr.reduce((s,x)=>s+Number(x[1].total||0),0));$('orders').innerHTML=arr.length?arr.map(([id,o])=>card(id,o)).join(''):'<div class="empty">Nenhum pedido ainda.</div>';conn('🟢 Firebase conectado • pedidos em tempo real','ok');},err=>{console.error(err);conn('🟠 Firebase conectou, mas as regras não permitem ler os pedidos.','warn');});
 unsubMenu=db.ref('settings/menu').on('value',snap=>renderMenuEditor(snap.val()?.items||DEFAULT_MENU),err=>console.error(err));
}
function card(id,o){const c=o.customer||{},items=(o.items||[]).map(x=>`${x.qty}x ${x.name} — ${money(x.price*x.qty)}`).join('<br>');const states=['recebido','preparando','saiu para entrega','entregue'];return `<article class="order"><div class="ordertop"><b>Pedido #${id.slice(-6)}</b><span class="status">${o.status||'recebido'}</span></div><h3>${c.name||'Cliente'}</h3><p>📱 ${c.phone||''}<br>📍 ${c.street||''}, ${c.number||''} — ${c.neighborhood||''}, ${c.city||''}/${c.uf||''} — CEP ${c.cep||''}<br>💳 ${c.payment||''}</p><hr><p>${items}</p><h3>Total: ${money(o.total)}</h3>${c.notes?`<p>📝 ${c.notes}</p>`:''}<div class="actions">${states.map(s=>`<button class="${o.status===s?'active':''}" data-status="${s}" data-id="${id}">${s.toUpperCase()}</button>`).join('')}</div></article>`}
window.setStatus=(id,status)=>db&&db.ref('orders/'+id).update({status});
function renderMenuEditor(items){const arr=Array.isArray(items)?items:Object.values(items||{});$('menuEditor').innerHTML=`<table class="menu-table"><thead><tr><th>Categoria</th><th>Produto</th><th>Descrição</th><th>Preço</th></tr></thead><tbody>${arr.map((x,i)=>`<tr><td><input data-i="${i}" data-k="cat" value="${esc(x.cat)}"></td><td><input data-i="${i}" data-k="name" value="${esc(x.name)}"></td><td><input data-i="${i}" data-k="desc" value="${esc(x.desc)}"></td><td><input data-i="${i}" data-k="price" type="number" step="0.01" min="0" value="${Number(x.price||0)}"></td></tr>`).join('')}</tbody></table>`;window.currentMenu=arr.map(x=>({...x}));}
$('saveMenu').onclick=async()=>{const arr=window.currentMenu||[];document.querySelectorAll('#menuEditor [data-i]').forEach(el=>{const i=Number(el.dataset.i),k=el.dataset.k;arr[i][k]=k==='price'?Number(el.value):el.value});try{await db.ref('settings/menu').set({items:arr,savedAt:Date.now()});alert('Cardápio salvo com sucesso!')}catch(e){console.error(e);alert('Não foi possível salvar. Verifique as regras do Realtime Database.')}};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
window.addEventListener('DOMContentLoaded',()=>{
 $('enter').onclick=()=>{if($('pin').value!==PIN)return alert('PIN incorreto.');$('login').classList.add('hidden');$('dashboard').classList.remove('hidden');sessionStorage.setItem('akatsukyAdmin','1');listen();};$('pin').addEventListener('keydown',e=>{if(e.key==='Enter')$('enter').click()});$('refresh').onclick=listen;$('logout').onclick=()=>{sessionStorage.removeItem('akatsukyAdmin');location.reload()};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-status]');if(b)window.setStatus(b.dataset.id,b.dataset.status);});
 try{if(!window.firebase)throw new Error('firebase');firebase.initializeApp(window.AKATSUKY_FIREBASE_CONFIG);db=firebase.database();conn('🟢 Firebase carregado • entre no painel para continuar','ok');}catch(e){console.error(e);conn('🔴 Não foi possível carregar o Firebase.','error');}
 if(sessionStorage.getItem('akatsukyAdmin')==='1'){$('login').classList.add('hidden');$('dashboard').classList.remove('hidden');listen();}
});
})();
