import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import { getDatabase, ref, onValue, update, set } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";
const db=getDatabase(initializeApp(firebaseConfig)),$=id=>document.getElementById(id);const PIN="1234";let unsubOrders=null,unsubMenu=null;
const DEFAULT_MENU=[["Combinados","Combinado Akatsuky","Seleção especial da casa.",59.90],["Combinados","Combinado Sushi","Variedade para compartilhar.",79.90],["Sushi","Uramaki Salmão","8 unidades.",32.90],["Sushi","Hot Roll","8 unidades.",29.90],["Sashimi","Sashimi Salmão","Fatias frescas.",39.90],["Temaki","Temaki Salmão","Salmão e arroz.",28.90],["Bebidas","Refrigerante Lata","Escolha o sabor.",6],["Bebidas","Água","Água mineral.",4]].map((x,i)=>({id:i+1,cat:x[0],name:x[1],desc:x[2],price:x[3]}));
function money(n){return Number(n).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function listen(){unsubOrders?.();unsubMenu?.();unsubOrders=onValue(ref(db,"orders"),snap=>{const data=snap.val()||{},arr=Object.entries(data).sort((a,b)=>(b[1].createdAt||0)-(a[1].createdAt||0));$("statOrders").textContent=arr.length;$("statNew").textContent=arr.filter(x=>x[1].status==="recebido").length;$("statTotal").textContent=money(arr.reduce((s,x)=>s+Number(x[1].total||0),0));$("orders").innerHTML=arr.length?arr.map(([id,o])=>card(id,o)).join(""):`<div class="empty">Nenhum pedido ainda.</div>`});unsubMenu=onValue(ref(db,"settings/menu"),snap=>renderMenuEditor(snap.val()?.items||DEFAULT_MENU));$("connection").textContent="🟢 Firebase conectado • atualização automática"}
function card(id,o){const c=o.customer||{},items=(o.items||[]).map(x=>`${x.qty}x ${x.name} — ${money(x.price*x.qty)}`).join("<br>");const states=["recebido","preparando","saiu para entrega","entregue"];return `<article class="order"><div class="ordertop"><b>Pedido #${id.slice(-6)}</b><span class="status">${o.status||"recebido"}</span></div><h3>${c.name||"Cliente"}</h3><p>📱 ${c.phone||""}<br>📍 ${c.street||""}, ${c.number||""} — ${c.neighborhood||""}, ${c.city||""}/${c.uf||""} — CEP ${c.cep||""}<br>💳 ${c.payment||""}</p><hr><p>${items}</p><h3>Total: ${money(o.total)}</h3>${c.notes?`<p>📝 ${c.notes}</p>`:""}<div class="actions">${states.map(s=>`<button class="${o.status===s?"active":""}" onclick="setStatus('${id}','${s}')">${s.toUpperCase()}</button>`).join("")}</div></article>`}
window.setStatus=(id,status)=>update(ref(db,"orders/"+id),{status});
function renderMenuEditor(items){const arr=Array.isArray(items)?items:Object.values(items||{});$("menuEditor").innerHTML=`<table class="menu-table"><thead><tr><th>Categoria</th><th>Produto</th><th>Descrição</th><th>Preço</th></tr></thead><tbody>${arr.map((x,i)=>`<tr><td><input data-i="${i}" data-k="cat" value="${String(x.cat||"").replaceAll('"','&quot;')}"></td><td><input data-i="${i}" data-k="name" value="${String(x.name||"").replaceAll('"','&quot;')}"></td><td><input data-i="${i}" data-k="desc" value="${String(x.desc||"").replaceAll('"','&quot;')}"></td><td><input data-i="${i}" data-k="price" type="number" step="0.01" min="0" value="${Number(x.price||0)}"></td></tr>`).join("")}</tbody></table>`;window.currentMenu=arr.map(x=>({...x}))}
$("saveMenu").onclick=async()=>{const arr=window.currentMenu||[];document.querySelectorAll("#menuEditor [data-i]").forEach(el=>{const i=Number(el.dataset.i),k=el.dataset.k;arr[i][k]=k==="price"?Number(el.value):el.value});try{await set(ref(db,"settings/menu"),{items:arr,savedAt:Date.now()});alert("Cardápio salvo com sucesso!")}catch(e){alert("Não foi possível salvar. Verifique as regras do Realtime Database.")}};
$("enter").onclick=()=>{if($("pin").value!==PIN)return alert("PIN incorreto.");$("login").classList.add("hidden");$("dashboard").classList.remove("hidden");sessionStorage.setItem("akatsukyAdmin","1");listen()};$("pin").addEventListener("keydown",e=>{if(e.key==="Enter")$("enter").click()});$("refresh").onclick=()=>listen();$("logout").onclick=()=>{sessionStorage.removeItem("akatsukyAdmin");location.reload()};if(sessionStorage.getItem("akatsukyAdmin")==="1"){$("login").classList.add("hidden");$("dashboard").classList.remove("hidden");listen()}
