import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import { getDatabase, ref, push, onValue } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getDatabase(app),$=id=>document.getElementById(id),brl=n=>Number(n).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const RESTAURANT_WHATSAPP="5519989860770";
const DEFAULT_MENU=[
["Combinados","Combinado Akatsuky","Seleção especial da casa.",59.90],["Combinados","Combinado Sushi","Variedade para compartilhar.",79.90],["Sushi","Uramaki Salmão","8 unidades.",32.90],["Sushi","Hot Roll","8 unidades.",29.90],["Sashimi","Sashimi Salmão","Fatias frescas.",39.90],["Temaki","Temaki Salmão","Salmão e arroz.",28.90],["Bebidas","Refrigerante Lata","Escolha o sabor.",6],["Bebidas","Água","Água mineral.",4]
].map((x,i)=>({id:i+1,cat:x[0],name:x[1],desc:x[2],price:x[3]}));
let menu=[...DEFAULT_MENU],cart=[],cat="Todos";
function renderCats(){const cats=["Todos",...new Set(menu.map(x=>x.cat))];$("cats").innerHTML=cats.map(x=>`<button class="cat ${x===cat?"on":""}" data-cat="${x}">${x}</button>`).join("");document.querySelectorAll(".cat").forEach(b=>b.onclick=()=>{cat=b.dataset.cat;renderCats();renderMenu()})}
function renderMenu(){$("menu").innerHTML=menu.filter(x=>cat==="Todos"||x.cat===cat).map(x=>`<article class="card product"><div class="catname">${x.cat}</div><h3>${x.name}</h3><p>${x.desc}</p><div class="price">${brl(x.price)}</div><button class="add" onclick="add(${x.id})">+ ADICIONAR</button></article>`).join("");renderCart()}
window.add=id=>{const x=cart.find(i=>i.id===id);x?x.q++:cart.push({id,q:1});renderCart()};window.del=id=>{const x=cart.find(i=>i.id===id);if(x&&x.q>1)x.q--;else cart=cart.filter(i=>i.id!==id);renderCart()};
function renderCart(){const total=cart.reduce((s,i)=>s+menu.find(x=>x.id===i.id).price*i.q,0);$("count").textContent=cart.reduce((s,i)=>s+i.q,0)+" itens";$("total").textContent=brl(total);$("cart").className=cart.length?"":"empty";$("cart").innerHTML=cart.length?cart.map(i=>{const x=menu.find(x=>x.id===i.id);return `<div class="cartrow"><span><b>${i.q}x</b> ${x.name}</span><b>${brl(x.price*i.q)}</b><button class="remove" onclick="del(${i.id})">−</button></div>`}).join(""):`Carrinho vazio. Adicione produtos acima.`}
async function loadMenu(){try{onValue(ref(db,"settings/menu"),snap=>{const v=snap.val();if(v&&Array.isArray(v.items)&&v.items.length)menu=v.items.map((x,i)=>({...x,id:Number(x.id)||i+1,price:Number(x.price)||0}));renderCats();renderMenu()},{onlyOnce:true});}catch(e){renderCats();renderMenu()}}
$("searchCep").onclick=async()=>{const c=$("cep").value.replace(/\D/g,"");if(c.length!==8)return alert("Digite um CEP válido.");try{const r=await fetch(`https://viacep.com.br/ws/${c}/json/`),d=await r.json();if(d.erro)return alert("CEP não encontrado.");$("street").value=d.logradouro||"";$("neighborhood").value=d.bairro||"";$("city").value=d.localidade||"";$("uf").value=d.uf||"";$("number").focus()}catch(e){alert("Não foi possível consultar o CEP agora. Preencha o endereço manualmente.")}};
$("cep").addEventListener("input",e=>{let c=e.target.value.replace(/\D/g,"").slice(0,8);e.target.value=c.length>5?c.slice(0,5)+"-"+c.slice(5):c});
$("orderForm").onsubmit=async e=>{e.preventDefault();if(!cart.length)return alert("Adicione produtos ao carrinho.");const total=cart.reduce((s,i)=>s+menu.find(x=>x.id===i.id).price*i.q,0);const order={createdAt:Date.now(),status:"recebido",customer:{name:$("name").value.trim(),phone:$("phone").value.trim(),cep:$("cep").value,street:$("street").value.trim(),number:$("number").value.trim(),neighborhood:$("neighborhood").value.trim(),city:$("city").value.trim(),uf:$("uf").value.trim().toUpperCase(),payment:$("payment").value,notes:$("notes").value.trim()},items:cart.map(i=>{const x=menu.find(x=>x.id===i.id);return{name:x.name,qty:i.q,price:x.price}}),total};try{const r=await push(ref(db,"orders"),order);localStorage.setItem("lastOrder",r.key);showTracking(r.key);openWhatsApp(r.key,order);cart=[];renderCart();}catch(err){alert("Não foi possível registrar o pedido. Verifique a conexão com o sistema.")}};
function openWhatsApp(id,o){const itens=o.items.map(x=>`${x.qty}x ${x.name} — ${brl(x.price*x.qty)}`).join("\n");const c=o.customer;const msg=`🍣 *NOVO PEDIDO - AKATSUKY DELIVERY SUSHI*\n\nPedido: #${id.slice(-6)}\nNome: ${c.name}\nCelular: ${c.phone}\n\n*Itens:*\n${itens}\n\n*Total:* ${brl(o.total)}\n*Pagamento:* ${c.payment}\n\n*Endereço:*\n${c.street}, ${c.number}\n${c.neighborhood} - ${c.city}/${c.uf}\nCEP: ${c.cep}${c.notes?`\n\nObs.: ${c.notes}`:""}`;window.open(`https://wa.me/${RESTAURANT_WHATSAPP}?text=${encodeURIComponent(msg)}`,"_blank")}
function showTracking(id){$("tracking").classList.remove("hidden");onValue(ref(db,"orders/"+id),s=>{const o=s.val();if(!o)return;const steps=["recebido","preparando","saiu para entrega","entregue"],idx=Math.max(0,steps.indexOf(o.status));$("trackingBox").innerHTML=`<p><b>Pedido #${id.slice(-6)}</b> <span class="status">${String(o.status).toUpperCase()}</span></p><p>Total: <b>${brl(o.total)}</b></p><div class="timeline">${steps.map((x,i)=>`<div class="step ${i<=idx?"active":""}">${x.toUpperCase()}</div>`).join("")}</div>`})}
let last=localStorage.getItem("lastOrder");if(last)showTracking(last);loadMenu();$("connection").textContent="🟢 Sistema online • pedidos em tempo real";
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("install").classList.add("show")});$("installBtn").onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("install").classList.remove("show")}else alert("No celular, use o menu do navegador e escolha 'Adicionar à tela inicial'.")};
renderCats();renderMenu();
